# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('Brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes_management.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, choices=[('h', 'Hombre'), ('m', 'Mujer'), ('u', 'Unisex')], default='h', max_length=1)),
                ('modelBrand', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes_management.ModelBrand')),
            ],
        ),
        migrations.CreateModel(
            name='ShoeInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, choices=[('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43')], default='27', max_length=2)),
                ('price', models.FloatField(default=0.0)),
                ('state', models.CharField(blank=True, choices=[('on', 'stacked'), ('of', 'sold')], default='on', max_length=2)),
                ('shoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes_management.Shoe')),
            ],
        ),
    ]
