# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelbrand',
            old_name='Brand',
            new_name='brand',
        ),
    ]
