# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_management', '0006_incoming_itemincoming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemincoming',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='shoeinstance',
            name='state',
            field=models.CharField(blank=True, choices=[('on', 'stacked'), ('of', 'vendido'), ('de', 'devolucion')], default='on', max_length=2),
        ),
    ]
