# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_management', '0007_auto_20170412_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='style',
            field=models.CharField(blank=True, choices=[('de', 'deportivo'), ('fo', 'formal')], default='de', max_length=2),
        ),
    ]
