# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_management', '0008_shoe_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes_management.Bill'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes_management.ShoeInstance'),
        ),
        migrations.AlterField(
            model_name='itemincoming',
            name='incoming',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes_management.Incoming'),
        ),
        migrations.AlterField(
            model_name='itemincoming',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoes_management.ShoeInstance'),
        ),
    ]
